<table>
    <tbody>
        <caption>{$errText}</caption>
        <tr>
            <th>Where</th>
{if empty($errContext)}
            <td>!!! UNSPECIFIED !!!</td>
{else}
            <td>{$errContext}</td>
{/if}
        </tr>
        <tr>
            <th>Code</th>
            <td>{$err}</td>
        </tr>
        <tr>
            <th>Sub-Code</th>
            <td>{$errCode}</td>
        </tr>
        <tr>
            <th>Query</th>
            <td>{$errQuery}</td>
        </tr>
        <tr>
            <th>Stack</th>
            <td>{$errStack}</td>
        </tr>
    </tbody>
</table>
